---
# tasks file for wordpress

  - name: Download and unarchive latest WordPress
    unarchive:
      src: https://wordpress.org/latest.tar.gz
      dest: "/var/www"
      remote_src: yes
      creates: "/var/www/wordpress" 
      mode: '0755'
    become: true

  - name: Set owner www-data
    file:
        path: "/var/www/wordpress"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
    become: true
  
  - name: Generating index.html
    template:
      src: '../templates/index.j2'
      dest: '/var/www/wordpress/index.html'
      mode: '0755'
    notify: Reload nginx config
    become: true
  
  - name: Generating wp-config.php
    template:
      src: '../templates/wp-config.php.j2'
      dest: '/var/www/wordpress/wp-config.php'
      mode: '0755'
    notify: Reload nginx config
    become: true
