---
# tasks file for mysql

  - name: Install mysql-server
    apt:
      name:
       'mysql-server={{ mysql_server_version }}-0ubuntu0.20.04.1'
      update_cache: true
    become: true

  - name: Start MySql and Enable
    service: 
      name: mysql
      state: started 
      enabled: true
    become: true

  - name: Install pip3
    apt: 
      name: python3-pip
    become: true
    
  - name: Make sure pymysql is present
    pip:
      name: pymysql
      state: present
    become: true
 
  - name: Move root credentials to remote
    template:
      src: '.my.cnf.j2'
      dest: '/root/.my.cnf'
      mode: '0755'
    become: true


  - name: Update mysql root password
    mysql_user:
        login_user: 'root'
        login_password: '{{ mysql_root_password }}'
        user: 'root'
        password: '{{ mysql_root_password }}'
        login_unix_socket: /var/run/mysqld/mysqld.sock
    become: true


  - name: Remove test database
    mysql_db: 
      name: test 
      state: absent
      login_user: 'root'
      login_password: '{{ mysql_root_password }}'
    become: true

  - name: Remove anonymous users 
    mysql_user: 
      user: ''
      state: absent
      login_user: 'root'
      login_password: '{{ mysql_root_password }}'
    become: true
  
  - name: Create a new database 
    mysql_db:
      login_user: 'root' 
      login_password: '{{ mysql_root_password }}'
      name: '{{ mysql_database_name }}' 
      state: present
    become: true

  - name: Create database user
    mysql_user:
      state: present
      login_user: 'root' 
      login_password: '{{ mysql_root_password }}'
      name: '{{ mysql_user }}' 
      password: '{{ mysql_user_password }}'
      priv:
        "{{ mysql_database_name }}.*:ALL,GRANT"
    become: true
